### PR TITLE
Admin media page is hidden for non-superusers

### PR DESCRIPTION
**Pull request by dcravenus**
Faculty should no longer be able to access the admin media page (add, modify or delete videos). A corresponding API change could provide more security.

### CODE REVIEW

**Comment by webnard** [comment]
Were corresponding changes ever made to the API?

**Comment by dcravenus** [comment]
No changes were made to the API since it looks like the API already prevents faculty from deleting. We may to look at whether we want owners to be able to delete as well as people who are given write access.

**Comment by webnard** [comment]
Hiding the media page prevents instructors from adding their own media—including through YouTube. Are all media requests to go through the HLR now?

**Comment by dcravenus** [comment]
:( I forgot about YouTube. But yeah, if they bring a DVD down the HLR should probably be totally in charge of it.

**Comment by webnard** [comment]
I think the amount of people using YouTube that need annotations are ver few, anyway.

**Pull request merged**
